spring:
  profiles:
    include: oauth
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    generate-unique-name: false
  h2:
    console:
      enabled: true
server:
  servlet:
    encoding:
      force-response: true  #머스테치 한글깨짐 오류 해결
    session:
      store-type: jdbc
